name: gotimer
description: "EsGo Timer — Go/Baduk oyuncuları için tasarlanmış, Byoyomi ve Kanada sistemlerini destekleyen modern turnuva zamanlayıcısı."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

  # Çoklu dil desteği
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Uygulama ikonlarını otomatik oluşturma
  flutter_launcher_icons: ^0.13.1

# ---- App Icon Ayarları ----
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#00000000"
    theme_color: "#000000"
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # ---- Asset Dosyaları ----
  assets:
    - assets/icon/
